CREATE TABLE questions (
  id SERIAL PRIMARY KEY,
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(1000) NOT NULL,
  password VARCHAR(1000) NOT NULL
);
